/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cuahangmevabe;

import bean.TableKhachHang;
import dao.KhachHangDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.KhachHang;

/**
 *
 * @author ADMIN
 */
public class KhachHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangJPanel
     */
    public KhachHangJPanel() {
        initComponents();
        jPanelKhacHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Khách Hàng");
        jLabel1.setToolTipText("");
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKhacHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneTen = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneSĐT = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneEmail = new javax.swing.JTextPane();
        jTextFieldTen = new javax.swing.JTextField();
        jTextFieldSĐT = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonTim = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelKhacHang.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKhacHang.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setToolTipText("");

        jTextPaneTen.setBackground(new java.awt.Color(237, 210, 210));
        jTextPaneTen.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextPaneTen.setForeground(new java.awt.Color(255, 51, 102));
        jTextPaneTen.setText("Tên");
        jScrollPane3.setViewportView(jTextPaneTen);

        jScrollPane4.setBackground(new java.awt.Color(255, 204, 204));

        jTextPaneSĐT.setBackground(new java.awt.Color(240, 216, 216));
        jTextPaneSĐT.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextPaneSĐT.setForeground(new java.awt.Color(255, 51, 102));
        jTextPaneSĐT.setText("SĐT");
        jTextPaneSĐT.setToolTipText("");
        jScrollPane4.setViewportView(jTextPaneSĐT);

        jTextPaneEmail.setBackground(new java.awt.Color(240, 212, 212));
        jTextPaneEmail.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextPaneEmail.setForeground(new java.awt.Color(255, 51, 102));
        jTextPaneEmail.setText("Ngày sinh");
        jScrollPane5.setViewportView(jTextPaneEmail);

        jTable1.setBackground(new java.awt.Color(248, 229, 229));
        jTable1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(17, 15, 15));
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(255, 204, 204));
        jScrollPane6.setViewportView(jTable1);

        jButtonSua.setBackground(new java.awt.Color(238, 213, 213));
        jButtonSua.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(255, 51, 102));
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setBackground(new java.awt.Color(238, 207, 207));
        jButtonXoa.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(255, 51, 102));
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonTim.setBackground(new java.awt.Color(246, 210, 210));
        jButtonTim.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonTim.setForeground(new java.awt.Color(255, 51, 102));
        jButtonTim.setText("Tìm");
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        jButtonThem.setBackground(new java.awt.Color(243, 210, 210));
        jButtonThem.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(255, 51, 102));
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahangmevabe/mb3.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKhacHangLayout = new javax.swing.GroupLayout(jPanelKhacHang);
        jPanelKhacHang.setLayout(jPanelKhacHangLayout);
        jPanelKhacHangLayout.setHorizontalGroup(
            jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKhacHangLayout.createSequentialGroup()
                .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhacHangLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButtonThem)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelKhacHangLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTen, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jTextFieldSĐT)
                            .addComponent(jTextFieldEmail))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelKhacHangLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKhacHangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelKhacHangLayout.setVerticalGroup(
            jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelKhacHangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhacHangLayout.createSequentialGroup()
                        .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSĐT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanelKhacHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonTim)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelKhacHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKhacHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
       /*jButtonThemActionPerformedthức được thực thi khi người dùng nhấp vào 
       nút "Thêm" (Add) và tạo một bản ghi khách hàng mới trong cơ sở dữ liệu
       dựa trên dữ liệu được nhập trong các trường văn bản */
        String name = jTextFieldTen.getText().toString();
        String sdt = jTextFieldSĐT.getText().toString();
        String email = jTextFieldEmail.getText().toString();

        if ( sdt.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui long khong bo trong");
        } else {
            KhachHangDao khachHangDao = new KhachHangDao();
            khachHangDao.createKhachHang(new KhachHang( name, sdt, email));
            loadData();
            xoaTrang();
        }

    }//GEN-LAST:event_jButtonThemActionPerformed
    
    public void loadData() {
        
        KhachHangDao khachHangDao = new KhachHangDao();
        jTable1.setModel(new TableKhachHang(khachHangDao.getKhachHang()));
    }

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
       /*jButtonSuaActionPerformedthức được thực thi khi người dùng nhấp vào
       nút "Sửa" (Sửa) và cập nhật bản ghi khách hàng hiện có trong cơ sở dữ liệu 
       dựa trên dữ liệu được nhập trong các trường văn bản.*/
        String name = jTextFieldTen.getText().toString();
        String sdt = jTextFieldSĐT.getText().toString();
        String email = jTextFieldEmail.getText().toString();

        if ( name.isEmpty() || sdt.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui long khong bo trong");
        } else {
            KhachHangDao khachHangDao = new KhachHangDao();
            khachHangDao.editKhachHang(new KhachHang( name, sdt, email));
            loadData();
            xoaTrang();
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:

        int output = JOptionPane.showConfirmDialog(null,
                "Xóa khách hàng đã chọn?", "Thông báo",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (output == JOptionPane.YES_OPTION) {
            String name = jTextFieldTen.getText().toString();
            String sdt = jTextFieldSĐT.getText().toString();
            String email = jTextFieldEmail.getText().toString();

            if (sdt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui long khong bo trong");
            } else {
                KhachHangDao khachHangDao = new KhachHangDao();
                khachHangDao.deleteKhachHang(new KhachHang( name, sdt, email));
                loadData();
                xoaTrang();
            }
        }


    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimActionPerformed
        String name = jTextFieldTen.getText().toString();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui long khong bo trong");
        } else {
            KhachHangDao khachHangDao = new KhachHangDao();
            jTable1.setModel(new TableKhachHang(khachHangDao.searchKhachHang(name)));
            xoaTrang();
        }
    }//GEN-LAST:event_jButtonTimActionPerformed

    public void xoaTrang() {
      
        jTextFieldTen.setText("");
        jTextFieldSĐT.setText("");
        jTextFieldEmail.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelKhacHang;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldSĐT;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextPane jTextPaneEmail;
    private javax.swing.JTextPane jTextPaneSĐT;
    private javax.swing.JTextPane jTextPaneTen;
    // End of variables declaration//GEN-END:variables

}
